<a href="https://colab.research.google.com/github/nvaughnn/PyTorch-Tut/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [7]:
# Addition
tensor_c = tensor_a + tensor_b
tensor_c

tensor([ 6,  8, 10, 12])

In [8]:
#Subtraction
tensor_d = tensor_b - tensor_a
tensor_d

tensor([4, 4, 4, 4])

In [9]:
#Mult
tensor_e = tensor_a * tensor_b
tensor_e

tensor([ 5, 12, 21, 32])

In [10]:
#Div
tensor_f = tensor_b / tensor_a
tensor_f

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
#Remainder
tensor_g = tensor_b % tensor_a
tensor_g

tensor([0, 0, 1, 0])

In [13]:
#Exponent
tensor_h = torch.pow(tensor_a,tensor_b)
tensor_h

tensor([    1,    64,  2187, 65536])

In [14]:
#Reassignment
#Use _ after operation to assign as the first argument. Not used as much.
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])